- name: Create and launch flask app
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 
    - name: install python
      apt:
        name: python3
        state: present
    - name: install pip
      apt:
        name: python3-pip
        state: present
    - name: install only in ec2 2
      apt:
        name: mysql-server
        state: present




    # - name: Add Docker GPG apt Key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present
    # - name: Add Docker Repository
    #   apt_repository:
    #     repo: deb https://download.docker.com/linux/ubuntu focal stable
    #     state: present
    # - name: Update apt and install docker-ce
    #   apt:
    #     name: docker-ce
    #     state: latest
    #     update_cache: true
    # - name: Install Docker Module for Python
    #   pip:
    #     name: docker

    # - name: Copy flask app to host
    #   copy:
    #     src: ./flask-app
    #     dest: /etc

    # - name: build docker app
    #   command: "chdir=/etc/flask-app sudo docker build . --tag python-docker"

    # - name: run the flask app
    #   command: "sudo docker run -d -p 80:5000 python-docker"